experiment_1:
  train:
    count: 100000 # 10ä¸‡
    qnet_sync_interval: 500
  tile_discard_agent:
    gamma: 0.98
    learning_rate: 0.0001
    epsilon: 0.1
    buffer_size: 1000
    batch_size: 32
    action_size: 14
    min_epsilon: 0.01
    decay_rate: 0.99999
  qnet:
    layer1: 38
    layer2: 256
    layer3: 128
    layer4: 64
